# Generated by Django 3.2.6 on 2021-09-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='img_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
